AWSTemplateFormatVersion: '2010-09-09'
Description: 'Tasky security group stack'

Parameters:
  VPCId:
    Type: String
    Description: VPC ID where the security group will be created
    
Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Allow SSH access from anywhere
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: 10.0.0.0/16
          Description: Allow MongoDB access from VPC

Outputs:
  EC2SecurityGroupId:
    Description: Security Group ID for EC2
    Value: !Ref EC2SecurityGroup